accum_grad: 1
batch_size: 1
batch_type: folded
best_model_criterion:
- - valid
  - acc
  - max
decoder: transformer
decoder_conf:
  dropout_rate: 0.1
  input_layer: embed
  linear_units: 2048
  num_blocks: 6
encoder: transformer
encoder_conf:
  attention_dropout_rate: 0.0
  attention_heads: 4
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  num_blocks: 12
  output_size: 256
grad_clip: 5
init: xavier_uniform
keep_nbest_models: 1
max_epoch: 5
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
optim: adam
optim_conf:
  lr: 1.0
patience: 0
scheduler: noamlr
scheduler_conf:
  warmup_steps: 1000
